apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: microservices
spec:
  ports:
  - port: 6379
    protocol: TCP
    name: mongodb
  selector:
    tier: data
  type: ClusterIP