apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
      tier: backend
  serviceName: mongodb
  replicas: 2
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: mongodb
        tier: backend
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - image: mongodb:5.6
        name: mongodb
        env:
        - name: MONGO_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-pass
              key: password
        ports:
        - containerPort: 3306
          name: mongodb
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /var/lib/mongodb
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pv-claim